name: ğŸ”„ Update README.md

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README.md with recent activity

    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v2

      - name: ğŸ‘¨â€ğŸ’» Update recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: 'ğŸ‘¨â€ğŸ’» Update README.md with recent activity'
          MAX_LINES: 7
